# XGBRegressor
model_params:
    n_estimators: 1250 #1000
    max_depth: 15
    learning_rate: 0.01
    subsample: 0.8
    colsample_bytree: 0.8
    min_child_weight: 32
    reg_lambda: 2
    eval_metric: mae
    tree_method: gpu_hist
    enable_categorical: False
    seed: 42

fit_params:
    verbose: 250
