# Core configuration

# == Default List ==
defaults:
    - paths: default
    - data: dl
    - model: BaseTSModel
    - trainer: default
    - hydra: default

# == Common ==
# Project name
project_name: Enefit-DL
# Experiment identifier
exp_id: null
# Number of random seeds for running experiments with the same setup
n_seeds: 1
# Random seed, currently picked automatically
seed: 42
# If True, use wandb to track training and evaluation processes
use_wandb: True
# If True, the experiment runs for only one fold
one_fold_only: False
# If True, perform full-training on the whole dataset after training and evaluation processes
full_train: False
