# Projet-specific paths
ROOT_DIR: ${hydra:runtime.cwd}

RAW_DATA_PATH: ${paths.ROOT_DIR}/data/raw/
PROC_DATA_PATH: ${paths.ROOT_DIR}/data/processed/

CONFIG_PATH: ${paths.ROOT_DIR}/config/

DUMP_PATH: ${paths.ROOT_DIR}/output/
